services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ~/clinic-project/mysql_data:/var/lib/mysql
      - ~/clinic-project/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    platform: linux/amd64   # ต้องใช้ emulation บน Apple Silicon
